# Site settings
title:          geekGirl
description:    "Minimal Jekyll theme for storytellers"
url:            "https://14richa.github.io"

# Author
author:
  name:         Richa Sharma
  url:          
  email:        richasharma1496@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
